#! /bin/bash

function cd() {
  if command -v z &> /dev/null; then
    # Use zoxide if it exists
    z $@
  else
    # Default to cd
    cd $@
  fi

  if command -v diral &> /dev/null; then
    source <(diral)
  fi
}

